### ISSUE TITLE
warning: you are attempting to open a lesson that is beyond your current lesson. are you sure you want to continue?

### ISSUE THREAD

**Issue by tmetz** [learn-co-curriculum/ruby-object-initialize-lab#14]
Many of the labs near the end of the Intro to Ruby Development unit raise the following warning when you load them in the Learn IDE:

_warning: you are attempting to open a lesson that is beyond your current lesson. are you sure you want to continue?_

I believe this may be because these labs are content for the Intro to Ruby Development unit but ALSO part of the Procedural Ruby and Object Oriented Ruby units that come later on, so the IDE thinks students are skipping ahead.  Is there any way to put these labs in one or the other, but not both?  Or alternatively squash the error?

**Comment by cjbrock** [comment]
Hi @tmetz! This error should only be triggered if you haven't completed a lesson previously. This could also happen if you had completed a lesson, but the lights hadn't triggered properly. If this happens, pop over to Ask a Question and one of the Technical Coaches should be able to assist you. 

Thank you for letting us know!
// <3 Corinna
